version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - gocritic
    - govet
    - misspell
    - revive
    - unconvert
  settings:
    revive:
      rules:
        - name: exported
        - name: unused-parameter
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports
